### ISSUE TITLE
App crash while trying to save attendants name

### ISSUE THREAD

**Issue by julimaster** [DrDab/TrcAttendance-Android#11]
#### Expected behavior
After clicking on save  attendant it should save successfully

#### Actual behavior
App crash instantly while trying to save  attendant name

#### How to reproduce
1. Open the app
2. Click on new file   
3. Enter the name of the csv file  then press okay
4.then enter the name of the attendant ,click save ,app will crash instantly 

***
* Browser/App version: TRC Attendance Logger version 1.0.0
* Operating system: Android marshmallow  6.0 ,tecno w3
***
#### Recording Of The Bug
![videotogif_2018.06.02_11.42.39.gif](https://cdn.steemitimages.com/DQmY8tQJA1uyna2Sh6N5TUtZP1N4vkPFgSFDbuHhVefRSV3/videotogif_2018.06.02_11.42.39.gif)

**Comment by DrDab** [comment]
Problem should be solved as of commit 01f13ce.
