### ISSUE TITLE
The app crashes when clicking CREATE MEETING when no column is filled

### ISSUE THREAD

**Issue by Icramss** [DrDab/TrcAttendance-Android#4]

**Comment by DrDab** [comment]
Hold on, I'm adding a few safeguards to the code to prevent a null textbox from being accepted.

**Comment by DrDab** [comment]
Can you please post a Logcat stack trace of the crash? Try reproducing the crash again with ADB Logcat on. Thank you 🙂

**Comment by DrDab** [comment]
Problem should be solved as of commit 01f13ce.
