### ISSUE TITLE
App crashes after clicking on Open file

### ISSUE THREAD

**Issue by Olamatto** [DrDab/TrcAttendance-Android#6]
#### Expected behavior
Application is expected to work perfectly well, after clicking on Open file to import

#### Actual Behavior 
After clicking on Open file, the app crashes. 

#### How to reproduce
- Launch the application 
- Click options button 
- Click on open file

<hr>

Application version: v1.0.0
Operating system: Android v7.0

#### Recording Of The Bug
https://cdn.steemitimages.com/DQmWbvqbTrCuJrJiNwPyY9aX8FPn2ZvR5ZLyAvK44W85MU7/videotogif_2018.06.02_07.49.33.gif

**Comment by DrDab** [comment]
Can you please post a Logcat stack trace of the crash? Try reproducing the crash again with ADB Logcat on. Thank you. :)

**Comment by DrDab** [comment]
Problem should be solved as of commit 01f13ce.

**Comment by Olamatto** [comment]
Ok, will be expecting that,  can you please label it as a bug
