### ISSUE TITLE
Clicking on Check-in and Check-out causes app to crash

### ISSUE THREAD

**Issue by Olamatto** [DrDab/TrcAttendance-Android#7]
#### Expected behavior
Application is expected to work perfectly well, after clicking on the check-in or check-out button

#### Actual Behavior 
After clicking on check-in or check-out the app crashes 

#### How to reproduce
- Launch the application 
- Scroll down 
- Click on Check-in or Check-out

Then app crashes 
<hr>

Application version: v1.0.0
Operating system: Android v7.0

#### Recording Of The Bug
https://cdn.steemitimages.com/DQmf5cdo7RKNCgumhgF8zUt47wSpw6mwkPBdzojucC5Fbox/videotogif_2018.06.02_09.11.11.gif

**Comment by DrDab** [comment]
Problem should be solved as of commit 01f13ce.

**Comment by Olamatto** [comment]
Ok, will be expecting that,  can you please label it as a bug.
