### ISSUE TITLE
App crash instantly after clicking on create meeting

### ISSUE THREAD

**Issue by julimaster** [DrDab/TrcAttendance-Android#8]
#### Expected behavior
After clicking on create the app should keep working.

#### Actual behavior
App crash instantly after clicking on create

#### How to reproduce
1. Open the app
2. Click on create, it will crash instantly
3. Bug is visible

***
* Browser/App version: TRC Attendance Logger version 1.0.0
* Operating system: Android marshmallow  6.0 ,tecno w3
***
#### Recording Of The Bug

![videotogif_2018.06.02_10.54.22.gif](https://cdn.steemitimages.com/DQmeQjDhUEmKPiL5dWgUFnMmyHhTZHPDqRn762wU4gqXpRS/videotogif_2018.06.02_10.54.22.gif)

**Comment by DrDab** [comment]
Problem should be solved as of commit 01f13ce.
