### ISSUE TITLE
App crash instantly after clicking on open file

### ISSUE THREAD

**Issue by julimaster** [DrDab/TrcAttendance-Android#9]
#### Expected behavior
After clicking on open file app should keep working as it is expected

#### Actual behavior
App crash instantly clicking on open file

#### How to reproduce
1. Open the app
2. Click on the menu option at the top of the app .
3. The click on open file app will crash instantly

***
* Browser/App version: TRC Attendance Logger version 1.0.0
* Operating system: Android marshmallow  6.0 ,tecno w3
***
#### Recording Of The Bug

![videotogif_2018.06.02_11.20.38.gif](https://cdn.steemitimages.com/DQmUoHCtNP2utNFhmN5Ywd2wem5B2aQkKwahh7Vbc4Xj2Uw/videotogif_2018.06.02_11.20.38.gif)

**Comment by DrDab** [comment]
Problem should be solved as of commit 01f13ce.
